# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba4aeed9f96de0e6f2df68556c4269af3bf8de5f218036f7c01273740c605eeca6cf8e3b107e509486a28476c666b8a04955f6d3a03b699c144a1f803459d38

test:
  secret_key_base: 3a6e8edca44b4228dbc4f0ef6592e8d56c85815555c6e0a5e73674dfeeca6dfd9bfa429995be665e5946c28541647e09c5895577ff008775fa8d08d9cf25d9ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
